module.exports = {
  apps: [
    {
      name: 'alumni-server',
      cwd: './server',
      script: 'node',
      args: './node_modules/tsx/dist/cli.mjs watch src/app.ts',
      env: {
        NODE_ENV: 'development',
        PORT: 3000,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      watch: false,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/server-error.log',
      out_file: './logs/server-out.log',
      merge_logs: true,
    },
    {
      name: 'alumni-client',
      cwd: './client',
      script: 'node',
      args: './node_modules/vite/bin/vite.js --port 5001',
      env: {
        NODE_ENV: 'development',
      },
      watch: false,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/client-error.log',
      out_file: './logs/client-out.log',
      merge_logs: true,
    },
    {
      name: 'alumni-admin',
      cwd: './admin',
      script: 'node',
      args: './node_modules/vite/bin/vite.js --port 5002',
      env: {
        NODE_ENV: 'development',
      },
      watch: false,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/admin-error.log',
      out_file: './logs/admin-out.log',
      merge_logs: true,
    },
  ],
};
