export default {
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  quoteProps: 'as-needed',
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: 'always',
  trailingComma: 'es5',
  endOfLine: 'lf',
  vueIndentScriptAndStyle: false,
  embeddedLanguageFormatting: 'auto',
};
